version: '3'

services:
  php:
    build:
      dockerfile: "Dockerfile"
    container_name: php-c
    restart: always
    volumes:
      - './src:/var/www/html'
      - './php.ini:/usr/local/etc/php/php.ini'

  chat_socket:
    build:
      dockerfile: "Dockerfile.socket"
    restart: always
    ports:
      - "50099:50099"
    volumes:
      - './src:/var/www/html'
      - './php.ini:/usr/local/etc/php/php.ini'

  notification_socket:
    build:
      dockerfile: "Dockerfile.notification_socket"
    restart: always
    ports:
      - "50100:50100"
    volumes:
      - './src:/var/www/html'
      - './php.ini:/usr/local/etc/php/php.ini'

  composer:
    image: composer:2.5.8
    volumes:
      - './src:/app'
    working_dir: '/app'

  apache:
    image: httpd:2.4
    restart: always
    ports:
      - "8000:80"
    volumes:
      - './src:/var/www/html'
      - './httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf'
    depends_on:
      - php

  mysql:
    container_name: "mysql"
    image: mysql:5.7
    restart: always
    command: --port=3406 --max_connections=5
    ports:
      - "3406:3406"
    environment:
      MYSQL_ROOT_PASSWORD: 1111
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./schema:/schema"

  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3406

  node:
    build:
      dockerfile: "Dockerfile.node"
    ports:
      - "3000:3000"
    command: npm run start
    volumes:
      - "./src:/usr/app"
